# -*- coding: utf-8 -*-
"""Resume_Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqSV-3eRnalvtLBFfF9TFioVWatLHBIS
"""

!pip install PyPDF2

from google.colab import files

# Upload the file
uploaded = files.upload()

# Get the file path
file_path = list(uploaded.keys())[0]

import re
import json
import PyPDF2

def parse_resume(file_path):
    with open(file_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        text = ''
        for page in reader.pages:
            text += page.extract_text()

    # Define regex patterns
    patterns = {
        "Name": r'Name:\s*(.*)',
        "Contact Information": r'Ph:\s*(.*)\nEmail:\s*(.*)\nLinkedIn:\s*(.*)',
        "Summary": r'SUMMARY\n([\s\S]*?)\nKEY EXPERTISE',
        "Education": r'EDUCATION\n([\s\S]*?)\nAWARDS AND SCHOLARSHIPS',
        "Experience": r'PROFESSIONAL EXPERIENCE\n([\s\S]*?)\nINTERNSHIPS',
        "Internships": r'INTERNSHIPS\n([\s\S]*?)\nPROJECTS',
        "Projects": r'PROJECTS\n([\s\S]*?)\nACHIEVEMENTS',
        "Skills": r'Skills:\s*(.*)',
        "Achievements": r'ACHIEVEMENTS\n([\s\S]*?)\nASSESSMENTS / CERTIFICATIONS',
        "Certifications": r'ASSESSMENTS / CERTIFICATIONS\n([\s\S]*?)\nSEMINARS / TRAININGS / WORKSHOPS',
        "Extracurricular Activities": r'EXTRA CURRICULAR ACTIVITIES\n([\s\S]*?)\nPERSONAL INTERESTS / HOBBIES',
        "Personal Interests": r'PERSONAL INTERESTS / HOBBIES\n([\s\S]*?)\nWEB LINKS',
        "Personal Details": r'PERSONAL DETAILS\n([\s\S]*)'
    }

    # Extract content
    resume_json = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, text)
        if match:
            resume_json[key] = match.group(1).strip()

    return json.dumps(resume_json, indent=4)

# Example usage
parsed_resume = parse_resume(file_path)
print(parsed_resume)